# Generated by Django 3.2.17 on 2023-02-07 09:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('hours', models.CharField(max_length=200)),
                ('opening_season', models.CharField(max_length=300)),
                ('has_ski_rentals', models.BooleanField(default=True)),
                ('has_ski_lessons', models.BooleanField(default=False)),
                ('offers_accommodation', models.BooleanField(default=False)),
                ('restaurants', models.IntegerField(default=0)),
                ('adults_ski_pass_price', models.IntegerField(default=0)),
                ('children_ski_pass_price', models.IntegerField(default=0)),
                ('gondola_lifts', models.BooleanField(default=True)),
                ('chair_lifts', models.BooleanField(default=True)),
                ('button_lifts', models.BooleanField(default=True)),
                ('moving_carpet_lifts', models.BooleanField(default=True)),
                ('easy_slopes', models.IntegerField(default=0)),
                ('intermediate_slopes', models.IntegerField(default=0)),
                ('difficult_slopes', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=10)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resorts.resort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resorts.resort')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
