# Generated by Django 3.2.17 on 2023-02-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='location',
            new_name='location_address',
        ),
        migrations.AlterField(
            model_name='resort',
            name='adults_ski_pass_price',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='resort',
            name='children_ski_pass_price',
            field=models.CharField(max_length=80),
        ),
    ]
