# Generated by Django 3.2.17 on 2023-02-07 15:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_auto_20230207_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='name',
            new_name='resort',
        ),
        migrations.AddField(
            model_name='resort',
            name='country',
            field=django_countries.fields.CountryField(default=True, max_length=80),
        ),
    ]
