# Generated by Django 3.2.17 on 2023-02-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_auto_20230207_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
