# Generated by Django 3.2.17 on 2023-03-15 17:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0005_auto_20230208_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='star_rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='star_rating',
            field=models.IntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
