# Generated by Django 3.2.17 on 2023-03-31 19:13

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0006_auto_20230315_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='contact',
            name='resort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resorts.resort'),
        ),
        migrations.AddField(
            model_name='resort',
            name='image_library',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='images'),
        ),
    ]
