# Generated by Django 3.2.17 on 2023-04-01 13:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0007_auto_20230331_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='image_library',
        ),
        migrations.AddField(
            model_name='resort',
            name='image_one',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='resort',
            name='image_three',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='resort',
            name='image_two',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
