# Generated by Django 3.2.17 on 2023-04-03 18:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0008_auto_20230401_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='body',
            field=models.TextField(default='Let us know what is on your mind'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Subject', max_length=500),
        ),
        migrations.AlterField(
            model_name='resort',
            name='image_one',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image one'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='image_three',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image three'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='image_two',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image two'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='main image'),
        ),
    ]
