# Generated by Django 3.2.17 on 2023-04-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0009_auto_20230403_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='resort',
        ),
    ]
