# Generated by Django 3.2.17 on 2023-04-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0010_remove_contact_resort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='Format: +46 000 000 000', max_length=15),
        ),
    ]
