# Generated by Django 3.2.17 on 2023-04-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0013_auto_20230405_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='resort',
        ),
    ]
